#pragma once
#include "types.h"

namespace S4MAP {

	enum class EGroundType : uint8_t {
		//0x0X
		WATER1 = 0,
		WATER2 = 1,
		WATER3 = 2,
		WATER4 = 3,
		WATER5 = 4,
		WATER6 = 5,
		WATER7 = 6,
		WATER8 = 7,
		WATER_BEACH = 8,

		// 0x1X
		GRASS = 16 + 0,
		GRASS_MOUNTAIN = 16 + 1,
		GRASS_ISLAND = 16 + 2,
		GRASS_DESERT = 16 + 4,
		GRASS_SWAMP = 16 + 5,
		GRASS_MUD = 16 + 7,
		GRASS_DARK = 16 + 8,
		GRASS_WEIRD = 16 + 9,
		GRASS_DUSTY = 16 + 12,
		GRASS_PAVEMENT = 16 + 13,

		// 0x2X
		MOUNTAIN = 32 + 0,
		MOUNTAIN_GRASS = 32 + 1,
		MOUNTAIN_SNOW = 32 + 3,

		// 0x3X
		BEACH = 48 + 0,

		// 0x4X
		DESERT = 64 + 0,
		DESERT_GRASS = 64 + 1,

		// 0x5X
		SWAMP = 80 + 0,
		SWAMP_GRASS = 80 + 1,

		// 0x6X
		RIVER1 = 96 + 0,
		RIVER2 = 96 + 1,
		RIVER3 = 96 + 2,
		RIVER4 = 96 + 3,

		// 0x7X
		UNIDENTIFIED_GRASS1 = 112 + 0,
		UNIDENTIFIED_GRASS2 = 112 + 1,
		UNIDENTIFIED_GRASS3 = 112 + 2,

		// 0x8X
		SNOW = 128 + 0,
		SNOW_MOUNTAIN = 128 + 1,

		// 0x9X
		MUD = 144 + 0,
		MUD_GRASS = 144 + 1,

		// extra stuff
		GLITCHED = 250,
	};
	enum class EResourceType :uint8_t {
		FISH,
		COAL_ORE,
		IRON_ORE,
		GOLD_ORE,
		SULFUR_ORE,
		STONE_ORE,
		//this will overwrite the resource ore "underneath it". Also explains why stone cutter/wood cutter don't work on mountains I guess
		STONE,
		WOOD
	};

	enum class EObjectType : uint8_t {
		Eiche = 1U,
		Buche,
		Esche,
		Linde,
		Birke,
		Silberpappel,
		Kastanie,
		Ahorn,
		Tanne,
		Fichte,
		Kokospalme,
		Dattelpalme,
		Walnuss,
		Korkeiche,
		Pinie,
		GemeinePinie,
		GrosserOlivenbaum,
		KleinerOlivenbaum,
		TropischeDattelpalme1,
		TropischeDattelpalme2,
		DunkelblaettrigeTropischePalme,
		TropischePalme,
		DunkleKastanie,
		DunkleEiche,
		DunklerAhorn,
		DunkleBuche,
		DunkleWalnuss,
		DunkleKorkeiche,
		DunkleTanne,
		NO_OBJECT0,
		DunklerDattelbaum,
		NO_OBJECT1,
		NO_OBJECT2,
		NO_OBJECT3,
		NO_OBJECT4,
		NO_OBJECT5,
		NO_OBJECT6,
		NO_OBJECT7,
		NO_OBJECT8,
		NO_OBJECT9,
		ZerklueftetesRiff,
		VerwildertesTrojanischesPferd,
		Ginsterbusch,
		Magnolie,
		Haselnuss,
		Holunder,
		Liguster,
		Weissdorn,
		Preiselbeere,
		HoherKaktus,
		KeltischesKreuz,
		Kuhskelett,
		MenschlichesSkelett,
		Wagenwrack,
		Schiffswrack,
		BraunerSteinGroesse4,
		BraunerSteinGroesse7,
		BraunerSteinGroesse5,
		BraunerSteinGroesse8,
		BraunerSteinGroesse3,
		BraunerSteinGroesse9,
		BraunerSteinGroesse1,
		BraunerSteinGroesse10,
		BraunerSteinGroesse2,
		BraunerSteinGroesse6,
		GrauerSteinGroesse6,
		GrauerSteinGroesse2,
		GrauerSteinGroesse10,
		GrauerSteinGroesse5,
		GrauerSteinGroesse3,
		GrauerSteinGroesse4,
		GrauerSteinGroesse9,
		GrauerSteinGroesse7,
		GrauerSteinGroesse1,
		GrauerSteinGroesse8,
		Nesseln,
		HellesGras,
		Dickblatt,
		Loewenzahn,
		Huflattich,
		Minze,
		Beifuss,
		Hirschzunge,
		Sauerampfer,
		Distel,
		NO_OBJECT10,
		Brunnenruine,
		NO_OBJECT11,
		Tuempel,
		Ruine,
		Vogelscheuche,
		Pilzkreis,
		RoetlicherStein,
		KleinerdunklerFels,
		RoetlicherFels,
		GrosserroetlicherFels,
		MittlererroetlicherFels,
		KleinerroetlicherFels,
		DunkleFelsen,
		MittlererdunklerFels,
		GrosserdunklerFels,
		KleinerDunklerStein,
		DunklesEfeu,
		BoeserFliegenpilz,
		BoeserSteinpilz,
		BoeserChampignon,
		SpitzesRiff,
		BreitesRiff,
		KleinesRiff,
		ZerklueftetesRiff2,
		DunkleHaselnuss,
		unklerLiguster,
		DunkleMagnolie,
		DunklePreiselbeere,
		MorbusDunklerStatuenboden,
		Saeule1,
		TrojanischesPferdimBau,
		TrojanischesPferd,
		Portal,
		GrosserKaktus,
		MittlererKaktus,
		KleinerKaktus,
		HolzstoeckeamRandbeiderzeitigkonstruiertenGebaeuden,
		SteinezumBauen1,
		SteinezumBauen2,
		SteinezumBauen3,
		SteinezumBauen4,
		SteinezumBauen5,
		SteinezumBauen6,
		SteinezumBauen7,
		SteinezumBauen8,
		SteinezumBauen9,
		SteinezumBauen10,
		SteinezumBauen11,
		SteinezumBauen12,
		SteinezumBauen13,
		DunkleSteinezumBauen1,
		DunkleSteinezumBauen2,
		DunkleSteinezumBauen3,
		DunkleSteinezumBauen4,
		DunkleSteinezumBauen5,
		DunkleSteinezumBauen6,
		DunkleSteinezumBauen7,
		DunkleSteinezumBauen8,
		DunkleSteinezumBauen9,
		DunkleSteinezumBauen10,
		DunkleSteinezumBauen11,
		DunkleSteinezumBauen12,
		DunkleSteinezumBauen13,
		DunklerTuempel,
		DunklerSchneemann,
		Saeule2,
		Saeulenecke1,
		Saeulenecke2,
		Saeulenecke3,
		Saeulenecke4,
		UmgefalleneSaeule,
		HalbeSaeule,
		HalbUmgefalleneSaeule,
		Maulbeere,
		Grab,
		AusgereifterWeinstock,
		Schilfgras,
		Moorbeere,
		Pampasgras,
		Schilfrohrklein,
		Schilfrohrmittel,
		Schilfrohrgross,
		Muschelgross,
		Muschelklein,
		RoteSeerose,
		WeisseSeerose,
		GelbeSeerose,
		TrockeneZweige,
		TrockenerZweig,
		TrockenerAst,
		TrockenerBusch,
		HalberKleinerRinderhaufen,
		Wuestenbusch,
		Wuestenstrauch,
		Fliegenpilz,
		Steinpilz,
		Champignon,
		BlumenweissLila,
		Blumenweiss,
		Blumenlila,
		BlumenweissRosa,
		Blumenrosa,
		KleinerRinderhaufen,
		MittlererRinderhaufen,
		GrosserRinderhaufen,
		Saeulenreihe1,
		Schild,
		KohlevorkommenSchild1,
		KohlevorkommenSchild2,
		KohlevorkommenSchild3,
		GoldvorkommenSchild1,
		GoldvorkommenSchild2,
		GoldvorkommenSchild3,
		EisenvorkommenSchild1,
		EisenvorkommenSchild2,
		EisenvorkommenSchild3,
		SteinvorkommenSchild1,
		SteinvorkommenSchild2,
		SteinvorkommenSchild3,
		SchwefelvorkommenSchild1,
		SchwefelvorkommenSchild2,
		SchwefelvorkommenSchild3,
		ueberreifesGetreidefeld,
		ReifesGetreidefeld,
		Agave,
		DunklesVolkreiferPilz,
		DunklesVolkhalbreiferPilz,
		DunklesVolknichtreiferPilz,
		Schneemann,
		// Interactive with SGround
		DunklesLandKonvertierungsEffekt,
		Bienennest,
		Saeulenreihe2,
		Saeulenbogen1,
		Saeulenbogen2,
		MagischesKraut,
		Pfaffenhuetchen,
		Schloss,
		GrosserTurmmitFeueraufderSpitze,
		RoemischeFreiheitsstatue,
		MosaikStatue,
		MosaikStatueimBau,
		MAMAGebaeude,
		NO_OBJECT12,
		EinbesondererBuschausdemDieneueWeltAddOn,
		TotengrabmitSpinnennetzenundKnochenschaedel,
		PRunenpyramide,
		DunklerSteinGroesse1,
		DunklerSteinGroesse2,
		DunklerSteinGroesse3,
		DunklerSteinGroesse4,
		DunklerSteinGroesse5,
		DunklerSteinGroesse6,
		DunklerSteinGroesse7,
		DunklerSteinGroesse8,
		DunklerSteinGroesse9,
		DunklerSteinGroesse10,
		DunklerroterSteinGroesse1,
		DunklerroterSteinGroesse2,
		DunklerroterSteinGroesse3,
		DunklerroterSteinGroesse4,
		DunklerroterSteinGroesse5,
		DunklerroterSteinGroesse6,
		DunklerroterSteinGroesse7,
		DunklerroterSteinGroesse8,
		DunklerroterSteinGroesse9,
		DunklerroterSteinGroesse10,
		SpitzesRiff2,
		DunkleSpuckpflanze,
		Sonnenblumen
	};
}