#pragma once
#include "types.h"

namespace S4MAP::S4MapFile::Segments {
	// taken from https://github.com/nyfrk/S4ModApi/blob/40be15b766e91fc3754349557dc406360b250001/S4ModApi/S4ModApi.h#L271
	enum class EBuildingType : uint8_t {
		NONE = 0,
		WOODCUTTERHUT, // building id 1
		FORESTERHUT,
		SAWMILL,
		STONECUTTERHUT,
		WATERWORKHUT,
		FISHERHUT,
		HUNTERHUT,
		SLAUGHTERHOUSE,
		MILL,
		BAKERY, // 10
		GRAINFARM,
		ANIMALRANCH,
		DONKEYRANCH,
		STONEMINE,
		IRONMINE,
		GOLDMINE,
		COALMINE,
		SULFURMINE,
		SMELTGOLD,
		SMELTIRON, // 20
		TOOLSMITH,
		WEAPONSMITH,
		VEHICLEHALL,
		BARRACKS,
		CHARCOALMAKER,
		TRAININGCENTER,
		HEALERHUT,
		AMMOMAKERHUT,
		GUNPOWDERMAKERHUT,
		LANDSCAPEMAKERHUT, // 30
		SHIPYARD,
		PORT,
		MARKETPLACE,
		STORAGEAREA,
		VINYARD,
		AGAVEFARMERHUT,
		TEQUILAMAKERHUT,
		BEEKEEPERHUT,
		MEADMAKERHUT,
		RESIDENCESMALL,// 40
		RESIDENCEMEDIUM,
		RESIDENCEBIG,
		SMALLTEMPLE,
		BIGTEMPLE,
		LOOKOUTTOWER,
		GUARDTOWERSMALL,
		GUARDTOWERBIG,
		CASTLE,
		MUSHROOMFARM,
		DARKTEMPLE, // 50
		FORTRESS,
		PORTA,
		PORTB,
		PORTC,
		PORTD,
		PORTE,
		PORTF,
		SHIPYARDA,
		SHIPYARDB,
		SHIPYARDC,
		SHIPYARDD,
		SHIPYARDE,
		SHIPYARDF,
		EYECATCHER01,
		EYECATCHER02,
		EYECATCHER03,
		EYECATCHER04,
		EYECATCHER05,
		EYECATCHER06,
		EYECATCHER07,
		EYECATCHER08,
		EYECATCHER09,
		EYECATCHER10,
		EYECATCHER11,
		EYECATCHER12,
		SHIPYARDG,
		SHIPYARDH,
		PORTG,
		PORTH,
		MANACOPTERHALL,
		SUNFLOWEROILMAKERHUT,
		SUNFLOWERFARMERHUT,
	};
	// https://github.com/nyfrk/S4ModApi/blob/40be15b766e91fc3754349557dc406360b250001/S4ModApi/S4ModApi.h#L225
	enum class EStackType : uint8_t {
		NONE = 0,
		AGAVE, // good id 1
		AMMO,
		ARMOR,
		AXE,
		BATTLEAXE,
		BLOWGUN,
		BOARD,
		BOW,
		BREAD,
		COAL, // 10
		FISH,
		FLOUR,
		GOAT,
		GOLDBAR,
		GOLDORE,
		GRAIN,
		GUNPOWDER,
		HAMMER,
		HONEY,
		IRONBAR,// 20
		IRONORE,
		LOG,
		MEAD,
		MEAT,
		PICKAXE,
		PIG,
		ROD,
		SAW,
		SCYTHE,
		SHEEP, // 30
		SHOVEL,
		STONE,
		SULFUR,
		SWORD,
		TEQUILA,
		WATER,
		WINE,
		BACKPACKCATAPULT,
		GOOSE,
		EXPLOSIVEARROW, // 40
		SUNFLOWEROIL,
		SUNFLOWER, // good id 42
	};
	enum class ESettlerType :uint8_t {
		NONE = 0,
		CARRIER, // settler id 1
		DIGGER,
		BUILDER,
		WOODCUTTER,
		STONECUTTER,
		FORESTER,
		FARMERGRAIN,
		FARMERANIMALS,
		FISHER,
		WATERWORKER,
		HUNTER,
		SAWMILLWORKER,
		SMELTER,
		MINEWORKER,
		SMITH,
		MILLER,
		BAKER,
		BUTCHER,
		SHIPYARDWORKER,
		HEALER,
		CHARCOALMAKER,
		AMMOMAKER,
		VEHICLEMAKER,
		VINTNER,
		BEEKEEPER,
		MEADMAKER,
		AGAVEFARMER,
		TEQUILAMAKER,
		SWORDSMAN_01,
		DARK_WARRIOR = SWORDSMAN_01,
		SWORDSMAN_02,
		SWORDSMAN_03,
		BOWMAN_01,
		DARK_THROWER = BOWMAN_01,
		BOWMAN_02,
		BOWMAN_03,
		MEDIC_01,
		MEDIC_02,
		MEDIC_03,
		AXEWARRIOR_01,
		AXEWARRIOR_02,
		AXEWARRIOR_03,
		BLOWGUNWARRIOR_01,
		BLOWGUNWARRIOR_02,
		BLOWGUNWARRIOR_03,
		SQUADLEADER,
		PRIEST,
		SABOTEUR,
		PIONEER,
		THIEF,
		GEOLOGIST,
		GARDENER,
		LANDSCAPER,
		DARKGARDENER,
		MUSHROOMFARMER,
		SHAMAN,
		SLAVED_SETTLER,
		TEMPLE_SERVANT,
		ANGEL_01,
		ANGEL_02,
		ANGEL_03,
		DONKEY,
		BACKPACKCATAPULTIST_01,
		BACKPACKCATAPULTIST_02,
		BACKPACKCATAPULTIST_03,
		SUNFLOWERFARMER,
		SUNFLOWEROILMAKER,
		MANACOPTERMASTER,

		UNK68 = 68, // The first 6 entities of a game are this. Maybe the spawn flags set in the editor?
		UNK69 = 69, // Probably door swordman of a tower
	};
	enum EMapFlag {
		/* naked map (no entities/buildings) properties */

		QUANTITY_GOODS_CHANGABLE = 1,
		ALLIANCES_CHANGABLE = 1 << 1,
		DISABLE_PLAYERCOUNT_CHANGE = 1 << 2,

		/* properties for all maps */
		DISABLE_MAP_PREVIEW = 1 << 3,
		ECONOMY_MODE = 1 << 4,
		// THIS IS ONLY PRESENT IN A VERY FEW SP/MP MAPS
		IS_ADD_ON_MAP_MAYBE = 1 << 5,
		IS_CAMPAIGN_MAP = 1 << 6,
		// conflict mode = 0 ; free settle mode = 1
		IS_SETTLE_MODE = 1 << 7,
		USE_NEW_WORLD_TEXTURES = 1 << 9
	};

	enum class EGameModeFlag :uint32_t {
		IS_MAP_TYPE_B = 1,
		IS_COOP = 2
	};

	enum class EStartResources : uint32_t {
		LOW = 1,
		MEDIUM,
		HIGH
	};

	enum class ETribe : uint32_t {
		ROMAN = 0,
		VIKING = 1,
		MAYAN = 2,
		DARKTRIBE = 3,
		TROJAN = 4,
		FREE_CHOICE = 255
	};

	enum class ETeam : uint8_t {
		TEAM_1 = 0,
		TEAM_2,
		TEAM_3,
		TEAM_4,
		TEAM_5,
		TEAM_6,
		TEAM_7,
		TEAM_8
	};

	enum class EPlayer : uint8_t {
		PLAYER_1 = 0,
		PLAYER_2,
		PLAYER_3,
		PLAYER_4,
		PLAYER_5,
		PLAYER_6,
		PLAYER_7,
		PLAYER_8,
		PLAYER_NONE = 255
	};

	enum class EPlayerType :uint8_t {
		FREE_SELECTION,
		HUMAN,
		COMPUTER
	};
}